# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanage', '0001_initial'),
        ('assetmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='media')),
                ('itunes', imagekit.models.fields.ProcessedImageField(upload_to='itunes/%Y/%m/%d/')),
                ('sasktel', imagekit.models.fields.ProcessedImageField(upload_to='sasktel/%Y/%m/%d/')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanage.Project')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanage.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='file_location',
            field=models.FilePathField(default=None, path=None),
        ),
    ]
