# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanage', '0003_auto_20160726_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_location',
            field=models.FilePathField(default='', path='C:\\'),
        ),
    ]
