# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanage', '0005_auto_20160726_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_location',
            field=models.FilePathField(default='', path='C:\\Users\\Simon\\Pictures\\poster_arts', recursive=True),
        ),
    ]
