# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanage', '0008_auto_20160727_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(default='')),
            ],
        ),
    ]
