# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanage', '0009_assettest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettest',
            name='file_path',
            field=models.FilePathField(default='', path='C:\\Users\\Simon\\Pictures\\poster_arts'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='itunes',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/itunes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='sasktel',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/sasktel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media/thumbnails/%Y/%m/%d/'),
        ),
    ]
