# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanage', '0010_auto_20160727_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='file_location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='file_size',
        ),
        migrations.AddField(
            model_name='asset',
            name='fichier',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
