# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('itunes', models.BooleanField(default=False)),
                ('google', models.BooleanField(default=False)),
                ('sasktel', models.BooleanField(default=False)),
                ('netflix', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Prequal', (('prequalready', 'Ready for Prequal'), ('prequalprogress', 'Prequal in progress'), ('prequaldone', 'Prequal Done'))), ('Qc', (('qcready', 'Ready for Qc'), ('qcprogress', 'Qc in progress'), ('qcdone', 'Qc Done'))), ('Packaging', (('packready', 'Ready for Packaging'), ('packprogress', 'Packaging in progress'), ('packdone', 'Packaging Done'))), ('Metadata', (('metaready', 'Ready for Metadata'), ('metaprogress', 'Metadata in progress'), ('metadone', 'Metadata Done')))], default='prequalready', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('itunes_code', models.CharField(blank=True, default='', max_length=250)),
                ('itc_user', models.CharField(blank=True, default='', max_length=250)),
                ('itc_password', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanage.Provider'),
        ),
    ]
